### ISSUE TITLE
Add logs folder to the gitignore

### ISSUE THREAD

**Issue by gdiepen** [felipepenha/py-greenhouse#29]
The logs folder will be modified every time that you do a run. Even if you did not make any changes in your code, the new timestamps will result in modified files in the log file which results in a lot commits

**Comment by felipepenha** [comment]
I will also delete the current logs.

**Comment by felipepenha** [comment]
Issue is being closed.

I was facing the problem that the logs were still being sent to the remote branch, but I solved it by running first

```
git rm --cached [file]
```

for each of the log files, because they were already being tracked.
